server:
  port: 9000

spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka