server:
  port: 9000

spring:
  shell:
    interactive:
      enabled: false
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true