spring:
    application:
        name: descovery-service
server:
    port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
    level:
        com.netflix.eureka: OFF
        com.netflix.discovery: OFF